const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Behaviors.EightDir,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Behaviors.custom.Acts.PushOutSolid,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{"3DCamera": 0},
	{Solid: 0},
	{Ground: 0},
	{Custom: 0},
	{"8Direction": 0},
	{Player: 0},
	{Tween: 0},
	{Cam3D: 0},
	{Browser: 0},
	{Trigger: 0},
	{Croush: 0},
	{Box: 0},
	{Wall: 0},
	{WallHome: 0},
	{Roof: 0},
	{Shadow: 0},
	{Grass: 0},
	{Touch: 0},
	{JoyStickBack: 0},
	{JoyStick: 0},
	{DragDrop: 0},
	{JoyStickDrag: 0},
	{JoyScreenBack: 0},
	{JoyScreen: 0},
	{ButtonJump: 0},
	{ButtonJumpCrouch: 0},
	{JoyTrigger: 0},
	{Dot: 0},
	{Кнопка: 0},
	{Cam_Height: 0},
	{Sensetivity: 0},
	{MoveSpeed: 0},
	{JumpStrenghts: 0},
	{FullScreen: 0},
	{Energy: 0},
	{Zaxis: 0},
	{Gravity: 0},
	{OnGround: 0},
	{PlayerZcheck: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	Ground: class extends self.I3DShapeInstance {},
	Player: class extends self.ISpriteInstance {},
	Cam3D: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Trigger: class extends self.ISpriteInstance {},
	Croush: class extends self.I3DShapeInstance {},
	Box: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	WallHome: class extends self.ISpriteInstance {},
	Roof: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Grass: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	JoyStickBack: class extends self.ISpriteInstance {},
	JoyStick: class extends self.ISpriteInstance {},
	JoyStickDrag: class extends self.ISpriteInstance {},
	JoyScreenBack: class extends self.ISpriteInstance {},
	JoyScreen: class extends self.ISpriteInstance {},
	ButtonJump: class extends self.ISpriteInstance {},
	ButtonJumpCrouch: class extends self.ISpriteInstance {},
	JoyTrigger: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	Кнопка: class extends self.IButtonInstance {}
}